# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_resturantlocation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantlocation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resturantlocation',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
