# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contents',
            field=models.TextField(help_text='seperate each items by comma'),
        ),
    ]
